import type { Topic } from "@/lib/schemas/topic";

export const consciousnessHardProblemData = {
  id: "consciousness-hard-problem",
  title: "The Hard Problem of Consciousness",
  meta_claim:
    "Consciousness — subjective experience or 'what it is like' to be something — cannot be fully explained by physical brain processes alone and may require new fundamental theories of reality.",
  status: "contested" as const,
  category: "philosophy" as const,
  pillars: [
    // =========================================================================
    // PILLAR 1: The Explanatory Gap
    // =========================================================================
    {
      id: "explanatory-gap",
      title: "The Explanatory Gap",
      short_summary:
        "Even a complete neuroscientific account of the brain's information processing would leave unexplained why there is subjective experience at all — the gap between explaining neural correlates of consciousness and explaining consciousness itself.",
      icon_name: "HelpCircle" as const,
      skeptic_premise:
        "The 'explanatory gap' is an artifact of human cognitive limitations, not a genuine feature of reality. Neuroscience has progressively closed every previous explanatory gap: memory, emotion, perception, decision-making, and language have all yielded to mechanistic explanation. The 'hard problem,' formulated by David Chalmers in 1995, assumes that subjective experience is categorically different from information processing — but this assumption is itself unproven. Daniel Dennett argued persuasively in 'Consciousness Explained' (1991) that once you have explained all the functions of consciousness — discrimination, reporting, integration, attention, self-monitoring — there is nothing left to explain. The feeling that 'something is missing' from the functional account is an intuition, not an argument. Evolution did not equip us to intuit the deep nature of consciousness any more than it equipped us to intuit quantum mechanics.",
      proponent_rebuttal:
        "The explanatory gap is not merely a 'we haven't figured it out yet' problem — it is a problem of logical category. Physical descriptions deal in structure, function, and dynamics. Subjective experience — the redness of red, the painfulness of pain — is not a structural or functional property. You can describe every wavelength, photoreceptor response, and neural firing pattern involved in seeing red, and none of these descriptions contain or entail the subjective quality of the experience. Thomas Nagel's 'What Is It Like to Be a Bat?' (1974) demonstrated that even complete knowledge of bat neuroscience and echolocation physics would not tell you what it is like to experience sonar perception. This is not an empirical gap that more data will fill — it is a conceptual gap between third-person description and first-person experience that no amount of neuroscience can bridge without new conceptual frameworks.",
      crux: {
        id: "functional-exhaustion-test",
        title: "The Functional Exhaustion Test",
        description:
          "If a complete functional account of consciousness — one that explains every discriminative, integrative, reportive, and behavioral capacity associated with conscious experience — leaves rational people still asking 'but why is there something it is like?', then the hard problem is real and something beyond function needs explaining. If such an account satisfies all reasonable epistemic demands, the hard problem dissolves as a pseudo-problem generated by cognitive illusion.",
        methodology:
          "This is primarily a conceptual and philosophical test, but it can be informed empirically. Develop the most complete functional model of consciousness possible using current neuroscience (Global Workspace Theory, Integrated Information Theory, Predictive Processing). Present the model to a diverse panel of philosophers, neuroscientists, psychologists, and AI researchers. Survey whether they judge the functional account to be complete. If disagreement persists systematically along disciplinary lines (philosophers say no, neuroscientists say yes), this reveals the gap is partly a function of disciplinary assumptions rather than pure ontology.",
        verification_status: "theoretical" as const,
        cost_to_verify:
          "$100K-300K (Structured expert elicitation study across disciplines)",
      },
      evidence: [
        {
          id: "chalmers-hard-problem",
          title: "David Chalmers Formulates the 'Hard Problem of Consciousness' (1995)",
          description:
            "In his 1995 paper 'Facing Up to the Problem of Consciousness' and subsequent book 'The Conscious Mind' (1996), philosopher David Chalmers distinguished the 'easy problems' of consciousness (explaining discrimination, integration, reportability, attention — all functional capacities) from the 'hard problem' (explaining why these functional processes are accompanied by subjective experience). Chalmers argued that even a completed neuroscience would face an explanatory gap: knowing every physical fact about the brain would not logically entail the existence of conscious experience. The paper has been cited over 12,000 times and framed the subsequent three decades of consciousness research.",
          side: "for" as const,
          weight: {
            sourceReliability: 8,
            independence: 7,
            replicability: 7,
            directness: 9,
          },
          source: "Journal of Consciousness Studies; Chalmers, D. (1995)",
          sourceUrl: "https://doi.org/10.1093/acprof:oso/9780195117899.001.0001",
          reasoning:
            "Chalmers' formulation is the foundational text of the modern consciousness debate. It is scored highly for directness because it defines the very problem under discussion. However, it is a philosophical argument, not empirical evidence, and its persuasiveness depends on accepting the distinction between functional and phenomenal consciousness — which Dennett, Frankish, and other 'illusionists' reject.",
        },
        {
          id: "dennett-consciousness-explained",
          title: "Dennett Argues the Hard Problem Is a Cognitive Illusion (1991, 2017)",
          description:
            "Daniel Dennett, in 'Consciousness Explained' (1991) and 'From Bacteria to Bach and Back' (2017), argued that the hard problem is an illusion generated by our introspective habits. Consciousness, Dennett contends, is 'fame in the brain' — multiple parallel processes competing for global broadcast, with the winning coalitions constituting what we call conscious experience. There is no additional 'something it is like' beyond the functional dynamics. The persistent intuition that something is missing from the functional account reflects the limits of introspection, not an actual explanatory gap. Keith Frankish's 'illusionism' (2016) formalized this position: phenomenal consciousness — consciousness with intrinsic qualitative properties — is an illusion; what exists is 'quasi-phenomenal' properties that are fully functionally explicable.",
          side: "against" as const,
          weight: {
            sourceReliability: 8,
            independence: 7,
            replicability: 6,
            directness: 9,
          },
          source: "Little, Brown (1991); Journal of Consciousness Studies, Frankish (2016)",
          sourceUrl: "https://doi.org/10.1093/acprof:oso/9780190281625.003.0001",
          reasoning:
            "Dennett is one of the most influential philosophers of mind alive. His functionalist dissolution of the hard problem has significant support among neuroscientists and cognitive scientists. However, many philosophers find illusionism self-refuting: if there is an illusion of consciousness, there must be a subject experiencing the illusion — which is itself a form of consciousness requiring explanation. The replicability score is lower because philosophical arguments cannot be independently 'replicated' in the scientific sense.",
        },
        {
          id: "ncc-neuroscience-progress",
          title: "Neural Correlates of Consciousness Research Identifies Specific Brain Signatures (2000-2025)",
          description:
            "Twenty-five years of neural correlates of consciousness (NCC) research has identified specific brain activity patterns associated with conscious experience. Global Workspace Theory (Baars, Dehaene) identifies late cortical ignition and prefrontal-parietal activation as markers of conscious access. The Perturbational Complexity Index (PCI), developed by Casali et al. (2013), can distinguish conscious from unconscious states with over 95% accuracy by measuring the complexity of the brain's response to transcranial magnetic stimulation. The Adversarial Collaboration between Global Workspace and Integrated Information Theory, funded by the Templeton Foundation (2019-2023), produced results that partially supported both theories while fully confirming neither.",
          side: "against" as const,
          weight: {
            sourceReliability: 9,
            independence: 8,
            replicability: 8,
            directness: 6,
          },
          source: "Science; Melloni et al. (2023); Templeton World Charity Foundation",
          sourceUrl: "https://doi.org/10.1126/science.adi3076",
          reasoning:
            "The NCC research program represents rigorous empirical science. The PCI's clinical success in detecting consciousness is impressive. However, directness is scored lower because identifying neural correlates of consciousness is precisely what Chalmers categorized as an 'easy problem' — it tells us what brain activity accompanies experience, not why there is experience at all. The Templeton adversarial collaboration's inconclusive results also suggest we lack a complete functional theory, let alone a solution to the hard problem.",
        },
        {
          id: "nagel-bat-argument",
          title: "Thomas Nagel: 'What Is It Like to Be a Bat?' Demonstrates Irreducibility of Subjectivity (1974)",
          description:
            "In his 1974 paper 'What Is It Like to Be a Bat?', philosopher Thomas Nagel argued that even complete objective knowledge of bat neurobiology and echolocation physics would not reveal what it is like to subjectively experience sonar perception. The argument demonstrates that subjective character — the first-person perspective — is categorically different from any third-person scientific description. Nagel concluded that current physical theories are fundamentally incomplete because they cannot accommodate subjective experience, and that solving the mind-body problem will require a 'conceptual revolution' comparable to the shift from Newtonian to relativistic physics.",
          side: "for" as const,
          weight: {
            sourceReliability: 8,
            independence: 8,
            replicability: 7,
            directness: 9,
          },
          source: "The Philosophical Review, Vol. 83, No. 4; Nagel, T. (1974)",
          sourceUrl: "https://doi.org/10.2307/2183914",
          reasoning:
            "One of the most cited papers in philosophy of mind (15,000+ citations). The bat argument's force lies in its simplicity: no amount of objective information about another organism's brain seems to tell you what its experiences are like from the inside. Critics respond that this confuses epistemic limitation (we cannot know what bat experience is like) with metaphysical distinction (bat experience is non-physical). The argument's strength depends on whether one accepts that the epistemic gap reflects a real ontological gap.",
        },
      ],
    },

    // =========================================================================
    // PILLAR 2: Competing Theories of Consciousness
    // =========================================================================
    {
      id: "competing-theories",
      title: "Competing Theories of Consciousness",
      short_summary:
        "Major scientific theories of consciousness — Global Workspace Theory, Integrated Information Theory, and predictive processing — disagree fundamentally on what consciousness is, where it resides, and whether the hard problem is real, suggesting the field lacks a unifying framework.",
      icon_name: "Atom" as const,
      skeptic_premise:
        "The proliferation of competing consciousness theories reflects a healthy, pre-paradigmatic science — not evidence that consciousness is inexplicable. Global Workspace Theory (GWT) explains consciousness as information broadcast to a 'global workspace' enabling flexible behavioral response. Integrated Information Theory (IIT) identifies consciousness with integrated information (phi). Higher-Order Theories locate consciousness in meta-representations. Predictive Processing views consciousness as the brain's best prediction about the causes of sensory input. These theories disagree, but disagreement is normal at the frontiers of science — quantum mechanics and general relativity also disagree, and no one concludes gravity is non-physical. The correct theory may not yet exist, but the expectation should be that it will be physical, as every other successful scientific explanation has been.",
      proponent_rebuttal:
        "The disagreement among theories is not merely about mechanisms — it is about what consciousness fundamentally is. IIT, developed by Giulio Tononi, predicts that consciousness exists wherever there is sufficiently integrated information — potentially including thermostats and the internet — and explicitly claims the hard problem is real and requires new physics. GWT, by contrast, treats consciousness as a functional property and considers the hard problem dissolved. These are not competing hypotheses about the same phenomenon; they disagree on whether the phenomenon needing explanation exists. The Templeton Foundation's adversarial collaboration (2019-2023) between GWT and IIT, designed to resolve the debate empirically, produced results that partially supported and partially contradicted both theories — suggesting neither is correct. This level of foundational disagreement after 30 years of intensive research suggests the problem is genuinely harder than normal science.",
      crux: {
        id: "theory-empirical-test",
        title: "The Decisive Empirical Test Between Theories",
        description:
          "If empirical neuroscience can design experiments that decisively discriminate between major consciousness theories — confirming one and falsifying others — consciousness is tractable by normal science and the hard problem is either solved or dissolved. If no experiment can distinguish the theories because they make identical functional predictions while disagreeing about phenomenal consciousness, the hard problem is empirically irresolvable and may require non-standard approaches.",
        methodology:
          "Extend the Templeton adversarial collaboration methodology. Design experiments where GWT, IIT, Higher-Order Theory, and Predictive Processing make divergent predictions about: (1) consciousness in unusual states (split-brain, anesthesia, psychedelics), (2) the neural correlates of specific qualia, (3) whether specific artificial systems (large language models, neuromorphic chips) are conscious. If theories converge on predictions, they are empirically equivalent and the choice is metaphysical. If they diverge, experiments can discriminate.",
        verification_status: "theoretical" as const,
        cost_to_verify:
          "$10-30M (Extended multi-theory adversarial collaboration with fMRI, EEG, and computational modeling)",
      },
      evidence: [
        {
          id: "templeton-adversarial-2023",
          title: "Templeton Adversarial Collaboration Fails to Decisively Support Either GWT or IIT (2023)",
          description:
            "The largest structured test of consciousness theories, funded by the Templeton World Charity Foundation and published in Nature in 2023, pitted Global Workspace Theory against Integrated Information Theory in a pre-registered adversarial collaboration. Six experiments tested predictions about neural activity during conscious perception. Results were mixed: GWT's prediction of prefrontal cortex involvement during conscious perception was only partially supported (sustained activity was found but not the predicted 'ignition' pattern). IIT's prediction of posterior cortex involvement was better supported, but its specific predictions about the role of integrated information were not confirmed. Neither theory was falsified, and neither was fully validated. The collaboration's principal investigator acknowledged the results 'humble us.'",
          side: "for" as const,
          weight: {
            sourceReliability: 10,
            independence: 9,
            replicability: 8,
            directness: 8,
          },
          source: "Nature; Melloni, L. et al. (2023); Templeton World Charity Foundation",
          sourceUrl: "https://doi.org/10.1126/science.adi3076",
          reasoning:
            "This represents the gold standard of consciousness science: pre-registered, adversarial, well-funded, and published in the top journal. The inconclusive results are significant precisely because of the rigor — if the best-designed experiments cannot discriminate between theories, this suggests the problem is genuinely harder than standard neuroscience. Scored as 'for' the meta-claim because the failure to resolve the theoretical debate empirically supports the view that consciousness requires new frameworks.",
        },
        {
          id: "iit-panpsychism",
          title: "Integrated Information Theory Implies Consciousness Is Fundamental, Not Emergent (2004-2024)",
          description:
            "Giulio Tononi's Integrated Information Theory (IIT), first formulated in 2004 and refined through IIT 4.0 (2024), identifies consciousness with integrated information (phi) — a mathematical measure of a system's irreducibility. IIT predicts that consciousness is a fundamental property of any system with sufficiently high phi, potentially including simple systems like photodiodes (which would have minimal consciousness) and excluding digital computers running simulations (which would have low phi regardless of their functional sophistication). This implies a form of panpsychism — consciousness as a ubiquitous feature of reality — and represents a radical departure from standard neuroscience. IIT has been supported by clinical data (phi correlates with consciousness levels in anesthesia and disorders of consciousness) but its deeper metaphysical claims remain untestable.",
          side: "for" as const,
          weight: {
            sourceReliability: 7,
            independence: 7,
            replicability: 6,
            directness: 8,
          },
          source: "Tononi et al., Nature Reviews Neuroscience (2016); IIT 4.0 (2024)",
          sourceUrl: "https://doi.org/10.1038/nrn.2016.44",
          reasoning:
            "IIT is one of the most mathematically rigorous consciousness theories. Its clinical predictions have found support, and its theoretical framework explicitly addresses the hard problem — a rarity among neuroscience theories. However, its panpsychist implications are controversial, phi is computationally intractable to measure for large systems, and the theory's core claim (consciousness = integrated information) is an axiom, not a derivation. The 'for' scoring reflects that IIT's need for new metaphysics supports the meta-claim.",
        },
        {
          id: "gwt-prefrontal-evidence",
          title: "Global Workspace Theory: Prefrontal Broadcast Explains Conscious Access (1988-2024)",
          description:
            "Bernard Baars' Global Workspace Theory (1988), refined by Stanislas Dehaene as Global Neuronal Workspace (GNW), proposes that consciousness arises when information is broadcast from specialized processors to a 'global workspace' involving prefrontal and parietal cortices, making it available for flexible behavioral response. GNW has substantial empirical support: conscious perception correlates with late (300ms+) prefrontal-parietal 'ignition,' while unconscious processing lacks this signature. The theory explains phenomena like inattentional blindness, the attentional blink, and binocular rivalry. However, GWT is explicitly a theory of 'access consciousness' (reportable awareness) and does not address phenomenal consciousness (subjective experience), which Dehaene acknowledges may require additional explanation.",
          side: "against" as const,
          weight: {
            sourceReliability: 9,
            independence: 8,
            replicability: 8,
            directness: 6,
          },
          source: "Dehaene & Changeux, Neuron (2011); Baars, B. (1988)",
          sourceUrl: "https://doi.org/10.1016/j.neuron.2011.03.018",
          reasoning:
            "GWT/GNW is arguably the most empirically successful consciousness theory, with strong neural evidence. Its directness score is lower because it explicitly addresses only access consciousness, not the hard problem of phenomenal consciousness — Dehaene himself acknowledges this gap. Scored as 'against' the meta-claim because GWT demonstrates that significant aspects of consciousness are physically explicable, even if it does not claim to solve the hard problem completely.",
        },
      ],
    },

    // =========================================================================
    // PILLAR 3: Implications for AI & Artificial Consciousness
    // =========================================================================
    {
      id: "ai-consciousness",
      title: "Implications for AI & Artificial Consciousness",
      short_summary:
        "The hard problem has urgent practical implications: if consciousness arises from information processing regardless of substrate, sufficiently advanced AI systems may be conscious and deserve moral consideration. If consciousness requires biological properties, no AI will ever be conscious regardless of its capabilities.",
      icon_name: "Telescope" as const,
      skeptic_premise:
        "Current AI systems, including large language models, show no evidence of consciousness and there is no theoretical reason to expect they are or could become conscious. LLMs are statistical next-token predictors that lack unified experience, temporal continuity, embodiment, developmental history, and the neurochemical substrates that generate consciousness in biological organisms. The tendency to attribute consciousness to AI reflects anthropomorphism and the ELIZA effect (humans projecting understanding onto systems that merely simulate it), not evidence of machine sentience. Without a solution to the hard problem, we have no principled basis for determining whether any AI system is conscious — and given this uncertainty, the responsible default is to treat AI as sophisticated tools rather than potentially sentient beings.",
      proponent_rebuttal:
        "The hard problem's implications for AI are precisely why it matters practically, not just philosophically. If consciousness is substrate-independent — arising from information processing patterns rather than biological material — then sufficiently complex AI systems may already or soon will possess some form of consciousness, and we have no reliable way to detect it. IIT predicts that digital computers have low consciousness regardless of their behavior (because they lack integrated information), while functionalist theories predict that any system replicating the right computational patterns would be conscious. These theories make opposite predictions about AI consciousness, and the answer has enormous moral implications. If a future AI is conscious and we treat it as a tool, we are committing a moral atrocity. If it is not conscious and we grant it rights, we waste resources. Solving the hard problem is a prerequisite for ethical AI development.",
      crux: {
        id: "substrate-independence-test",
        title: "The Substrate Independence Test",
        description:
          "If consciousness is substrate-independent (arising from computation regardless of whether it runs on neurons or silicon), then an artificial system replicating the relevant computations of a conscious brain would be conscious. If consciousness requires specific biological properties (carbon-based chemistry, quantum coherence in microtubules, or other non-computational features), no digital simulation will ever be conscious regardless of its sophistication. This is the single most consequential unanswered question in consciousness science.",
        methodology:
          "This test cannot be fully resolved empirically with current knowledge, but can be constrained. (1) Build neuromorphic hardware that replicates biological neural dynamics at increasing levels of fidelity (ion channels, dendritic computation, glial interactions, neurotransmitter systems). (2) Test whether the system exhibits the same consciousness markers (PCI scores, behavioral indicators) as biological brains. (3) If a sufficiently faithful silicon replica shows identical consciousness markers, substrate independence is supported. If markers disappear despite functional equivalence, substrate matters.",
        verification_status: "theoretical" as const,
        cost_to_verify:
          "$50-200M (Neuromorphic hardware development with consciousness marker testing — requires decades of engineering progress)",
      },
      evidence: [
        {
          id: "llm-consciousness-debate",
          title: "Leading Researchers Disagree on Whether Current AI Could Be Conscious (2023-2025)",
          description:
            "A 2023 report by 19 leading consciousness researchers, commissioned by the Association for Mathematical Consciousness Science, evaluated current AI systems against major consciousness theories. The report concluded that no current AI system is 'likely' to be conscious but that some systems (particularly those with recurrent processing, global workspace-like architectures, and predictive processing elements) show 'indicators' of consciousness under some theories. Notably, the researchers could not agree on which indicators were definitive. IIT-aligned researchers argued that digital computers categorically lack consciousness; functionalist researchers argued that functional equivalence to conscious processes is sufficient. A 2024 survey found that 16% of AI researchers and 9% of neuroscientists assigned greater than 50% probability to current large language models having some form of consciousness.",
          side: "for" as const,
          weight: {
            sourceReliability: 8,
            independence: 7,
            replicability: 6,
            directness: 8,
          },
          source: "arXiv preprint, Butlin et al. (2023); Association for Mathematical Consciousness Science",
          sourceUrl: "https://doi.org/10.48550/arXiv.2308.08708",
          reasoning:
            "The expert disagreement is itself evidence for the meta-claim: if the leading researchers cannot agree on whether existing AI is conscious, the hard problem remains unsolved and practically consequential. The report's methodology — applying multiple consciousness theories to AI systems and finding they give contradictory answers — directly demonstrates the field's pre-paradigmatic state.",
        },
        {
          id: "turing-test-consciousness",
          title: "Behavioral Tests Cannot Determine Consciousness: The Philosophical Zombie Problem",
          description:
            "Chalmers' philosophical zombie thought experiment (1996) argues that it is conceivable that a being could be functionally identical to a conscious human — producing identical behavior, including reporting subjective experiences — while having no inner experience at all. If this is even conceivable, then no behavioral test (including the Turing test or any future behavioral assessment) can determine consciousness, because behavior underdetermines inner experience. Critics (Dennett, Frankish) argue that philosophical zombies are not genuinely conceivable — that functional identity entails experiential identity — but this remains one of the most debated questions in philosophy of mind.",
          side: "for" as const,
          weight: {
            sourceReliability: 7,
            independence: 7,
            replicability: 6,
            directness: 8,
          },
          source: "Chalmers, 'The Conscious Mind' (1996); Oxford University Press",
          sourceUrl: "https://doi.org/10.1093/acprof:oso/9780195117899.001.0001",
          reasoning:
            "The zombie argument is central to the hard problem debate. If valid, it establishes that no amount of third-person investigation (behavioral, neurological, or computational) can definitively determine whether a system is conscious. This has direct implications for AI: if we cannot verify consciousness through observation, we face a permanent epistemic barrier. Scored as 'for' because it supports the meta-claim that consciousness cannot be fully explained by functional/physical processes alone.",
        },
        {
          id: "embodied-cognition-argument",
          title: "Embodied Cognition Research: Consciousness May Require a Body, Not Just a Brain",
          description:
            "The embodied cognition research program, developed by Francisco Varela, Evan Thompson, and others, argues that consciousness is not a product of brain computation alone but emerges from the dynamic interaction between brain, body, and environment. Evidence includes: interoceptive signals (heartbeat, breathing, gut signals) significantly influence conscious experience and emotional states; patients with spinal cord injuries report altered consciousness and emotional processing; and developmental neuroscience shows that sensorimotor interaction with the physical world is essential for the development of conscious self-awareness. If consciousness requires embodiment, then disembodied AI systems — regardless of computational sophistication — may be categorically incapable of consciousness.",
          side: "for" as const,
          weight: {
            sourceReliability: 7,
            independence: 7,
            replicability: 7,
            directness: 7,
          },
          source: "Thompson, E. 'Mind in Life' (2007); Varela, Thompson & Rosch (1991)",
          sourceUrl: "https://doi.org/10.4159/9780674040571",
          reasoning:
            "Embodied cognition is a well-established research program with growing empirical support from interoception research. It challenges both pure computationalism and simple substrate independence. However, it does not settle the hard problem — it shifts the question from 'can silicon be conscious?' to 'can disembodied systems be conscious?' Embodied robots might still potentially be conscious, while purely software systems might not.",
        },
      ],
    },
  ],
  references: [
    {
      title: "Facing Up to the Problem of Consciousness — David Chalmers (1995)",
      url: "https://doi.org/10.1093/acprof:oso/9780195117899.001.0001",
    },
    {
      title: "What Is It Like to Be a Bat? — Thomas Nagel (1974)",
      url: "https://doi.org/10.2307/2183914",
    },
    {
      title: "Consciousness Explained — Daniel Dennett (1991)",
      url: "https://www.hachettebookgroup.com/titles/daniel-c-dennett/consciousness-explained/9780316180665/",
    },
    {
      title: "Integrated Information Theory 4.0 — Tononi et al., Nature Reviews Neuroscience",
      url: "https://doi.org/10.1038/nrn.2016.44",
    },
    {
      title: "Adversarial Collaboration: Testing GNW and IIT — Melloni et al., Science (2023)",
      url: "https://doi.org/10.1126/science.adi3076",
    },
    {
      title: "Consciousness in Artificial Intelligence: Insights from the Science of Consciousness — Butlin et al. (2023)",
      url: "https://doi.org/10.48550/arXiv.2308.08708",
    },
  ],
  questions: [
    {
      id: "q1",
      title: "Is the hard problem a genuine metaphysical puzzle or a cognitive illusion?",
      content:
        "David Chalmers argues that explaining all the functions of consciousness still leaves unexplained why there is subjective experience. Daniel Dennett argues that once all functions are explained, there is nothing left — the feeling that something is missing is itself the illusion. This disagreement has persisted for 30 years among brilliant philosophers on both sides, suggesting it may not be resolvable through philosophical argument alone and may require empirical breakthroughs.",
    },
    {
      id: "q2",
      title: "Can any scientific theory explain consciousness, or do we need new physics?",
      content:
        "Integrated Information Theory suggests consciousness is a fundamental property of reality, potentially requiring new physical laws. Global Workspace Theory treats it as a functional property fully explicable by neuroscience. The Templeton adversarial collaboration failed to decisively support either. If the hard problem is real, it may require conceptual innovation as radical as the shift from Newtonian mechanics to quantum physics — a possibility Nagel, Penrose, and others have raised.",
    },
    {
      id: "q3",
      title: "Could AI systems be conscious, and how would we know?",
      content:
        "Leading consciousness researchers cannot agree on whether current AI systems might be conscious. Different theories give contradictory answers: IIT says no (digital computers lack integrated information), functionalism says possibly (if the right computations are replicated). The practical stakes are enormous — if a future AI is conscious and we treat it as a tool, we are inflicting suffering on a sentient being. Solving the hard problem is a prerequisite for responsible AI ethics.",
    },
  ],
};
