import type { Topic } from "@/lib/schemas/topic";

export const spaceExplorationValueData = {
  id: "space-exploration-value",
  title: "Is Space Exploration Worth It?",
  meta_claim:
    "Government-funded space exploration provides sufficient scientific, economic, and strategic returns to justify its cost.",
  status: "contested" as const,
  category: "science" as const,
  // ── Stage 1: the wow fact shown above everything ──
  keystone_fact: {
    statement:
      "Americans routinely guess NASA eats a big slice of the federal budget — it's about 0.4% (~$24.9B). And the famous '$7–14 back per dollar' spin-off figure is a 1970s promotional estimate, not a measured return; the honest case rests on real technologies (GPS, water purification, medical imaging) and a ~$570B global space economy, not a magic multiplier.",
    confidence: 85,
    source:
      "NASA FY2024 budget (~$24.9B, ~0.4% of federal spending); NASA Spinoff database; WEF/McKinsey space-economy forecast (2024)",
    sourceUrl: "https://spinoff.nasa.gov/",
  },
  // ── Stage 2: the honest 3-sentence case ──
  simple_case: [
    "The case for space spending is usually argued with two shaky numbers — that NASA is a big budget line and that it returns '$7–14 per dollar' — and both are wrong: NASA is about 0.4% of federal spending, and the famous multiplier is a 1970s promotional estimate, not a measured return.",
    "Strip away the hype and a real case remains: genuine spin-off technologies (GPS, water purification, medical imaging, satellite weather and climate data with no Earth-bound substitute), a ~$570B global space economy, and demonstrated planetary defense (NASA's DART actually moved an asteroid).",
    "So the honest debate isn't 'is space a waste?' — it's a small, partly-justified line item — but where the marginal dollar should go: robotic missions win decisively on science-per-dollar, while crewed missions are sold on inspiration and STEM pipelines that are real but hard to price.",
  ],
  pillars: [
    {
      id: "economic-returns-spinoffs",
      title: "Economic Returns & Spin-offs",
      short_summary:
        "The popular \"$7-14 back per dollar\" spin-off figure turns out to be a 1970s-90s estimate built on an assumed rate of return, not measured revenue; better-grounded analyses land closer to 2-3:1. The honest case for funding rests on the genuine technologies and the large, fast-growing commercial space sector — not a magic multiplier.",
      icon_name: "Scale" as const,
      skeptic_premise:
        "NASA's ~$24.9B FY2024 budget could instead seed domestic priorities — childcare, water infrastructure, housing — with nearer-term, easier-to-measure impact. Space tourism in particular looks like a billionaire's playground riding on taxpayer-funded launch capability. And the spin-off story is oversold: Tang was a Kraft product NASA merely flew (not invented), and the famous \"$7-14 per dollar\" multiplier is a promotional estimate, not a measured return. Strip away the exaggeration and the question is whether the genuine benefits justify spending public money on space rather than on people who lack basics today.",
      proponent_rebuttal:
        "Skip the inflated multiplier and the case still holds. Real, attributable spin-offs include advances embedded in GPS, water purification, medical imaging, and satellite communications, and NASA has documented over 2,000 such technology transfers since 1976. The commercial space economy reached roughly $570B in 2023 and a 2024 WEF/McKinsey forecast projects ~$1.8T by 2035. SpaceX's reusable rockets cut launch costs dramatically, seeding a private sector that now dwarfs government spending — even if the headline ROI ratio was never solid.",
      crux: {
        id: "space-economy-roi",
        title: "Space Investment ROI Calculation",
        description:
          "Comprehensive analysis of direct and indirect economic returns from government space spending, including spin-off technologies, commercial sector growth, and opportunity costs.",
        methodology:
          "Track all NASA-funded patents and their commercial applications. Calculate revenue generated by spin-off industries. Compare to counterfactual spending on social programs using economic multiplier models.",
        equation:
          "\\text{ROI} = \\frac{\\sum_{t} (\\text{Spin-off Revenue}_t + \\Delta\\text{GDP}_{\\text{space sector},t})}{\\sum_{t} \\text{Government Investment}_t}",
        verification_status: "theoretical" as const,
        cost_to_verify: "$500K (Comprehensive economic analysis)",
        falsification: {
          supporter_flip:
            "If a rigorous accounting found government space spending returns less than it costs once you use measured spin-off revenue (not the promotional multiplier) and compare against the counterfactual of spending the money elsewhere, the economic case for public funding would weaken to 'nice-to-have, not self-justifying.'",
          skeptic_flip:
            "A skeptic who calls it a waste should weigh that NASA is only ~0.4% of the budget, that documented spin-offs and a ~$570B global space sector are real (even without the inflated multiplier), and that launch-cost collapse seeded a private industry now dwarfing government spending.",
          common_ground:
            "Both sides agree the headline '$7–14 per dollar' ROI figure is a promotional estimate, not a measured return.",
          live_disagreement:
            "Whether government space spending's genuine but hard-to-measure returns (spin-offs, commercial catalysis, strategic infrastructure) exceed what the same money would yield spent on Earth-bound priorities.",
        },
      },
      evidence: [
        {
          id: "nasa-spinoff-analysis",
          title: "NASA Spin-off Economic Impact Analysis",
          description:
            "NASA's annual Spinoff publication has profiled more than 2,000 technologies transferred to the private sector since 1976. The widely-cited '$7-14 (or higher) per dollar' ROI figures trace to NASA-commissioned econometric studies from the 1970s-90s that *assumed* an average rate of return for R&D rather than measuring spin-off revenue directly; critics note attribution is inflated since many technologies had parallel commercial development, and more conservative analyses suggest ratios closer to 2-3:1.",
          side: "for" as const,
          weight: {
            sourceReliability: 4,
            independence: 2,
            replicability: 3,
            directness: 4,
          },
          source: "NASA Spinoff (spinoff.nasa.gov); critique: John Pike / FAS",
          sourceUrl: "https://spinoff.nasa.gov/",
          reasoning:
            "The count of 2,000+ documented spin-offs is verifiable, but the high ROI multipliers are promotional estimates built on generous assumptions, not measured returns. Weights de-inflated: low independence (self-reported), low replicability (headline multiplier not reproducible from primary data).",
        },
        {
          id: "space-economy-projections",
          title: "Space Economy Projected at $1.8 Trillion by 2035",
          description:
            "A 2024 World Economic Forum report produced with McKinsey & Company projects the global space economy will grow from $630B (2023) to $1.8T by 2035 (~9% annual growth), driven by space-based and -enabled services in communications, positioning/navigation/timing, and Earth observation. This is a forecast, not a measured return on government spending.",
          side: "for" as const,
          weight: {
            sourceReliability: 6,
            independence: 6,
            replicability: 4,
            directness: 4,
          },
          source: "World Economic Forum & McKinsey, 'Space: The $1.8 Trillion Opportunity' (2024)",
          sourceUrl: "https://www.mckinsey.com/featured-insights/themes/the-space-economy-is-projected-to-reach-1-8-trillion-by-2035",
          reasoning:
            "Credible institutions, but the figure is a speculative 11-year forecast with wide error bars and only indirectly bears on whether *government* space spending pays off. Directness lowered accordingly; corrected the 2023 base ($630B, not $469B) and attribution (WEF/McKinsey, not Morgan Stanley).",
        },
        {
          id: "opportunity-cost-analysis",
          title: "Opportunity Cost: NASA's Budget vs. Social Programs",
          description:
            "NASA's enacted FY2024 budget was $24.875B — money that could instead fund domestic priorities such as childcare, water infrastructure, or housing. But the zero-sum framing is weak: NASA is only about 0.4% of the ~$6.8T federal budget, so its appropriation is far smaller than the cost of most universal social programs (e.g. universal pre-K is generally estimated in the tens of billions per year).",
          side: "against" as const,
          weight: {
            sourceReliability: 6,
            independence: 7,
            replicability: 6,
            directness: 5,
          },
          source: "The Planetary Society (NASA FY2024 budget, $24.875B)",
          sourceUrl: "https://www.planetary.org/space-policy/nasas-fy-2024-budget",
          reasoning:
            "Corrected the budget figure ($24.875B enacted, not $25.4B) and federal share (~0.4%, not 0.5%). De-inflated weights and softened the claim: the specific pre-K/clean-water/veteran-homelessness dollar substitutions were not traceable to CBO/Brookings, and the comparison rests on a contestable zero-sum assumption.",
        },
        {
          id: "private-space-revenue",
          title: "Commercial Space Revenue Now Dwarfs Government Spending",
          description:
            "Per the Space Foundation's Space Report 2024, the global space economy reached $570B in 2023, of which commercial revenue was about $445B (78%) versus ~$125B in government spending. SpaceX alone was valued at roughly $180B in a December 2023 tender offer. The large and growing commercial share suggests government seed investment helped catalyze a substantial private sector.",
          side: "for" as const,
          weight: {
            sourceReliability: 7,
            independence: 6,
            replicability: 6,
            directness: 5,
          },
          source: "Space Foundation, The Space Report 2024 Q2; SpaceX valuation via Bloomberg (Dec 2023)",
          sourceUrl: "https://www.spacefoundation.org/2024/07/30/the-space-report-2024-q2-shows-record-launch-pace-nasas-push-for-artemis-innovation-for-cleaner-rocket-fuels-new-tech-for-noaa-satellites/",
          reasoning:
            "Corrected outdated figures: commercial revenue is ~$445B of a $570B total (the old $384B was a stale Space Foundation number); the $8.5B 'private investment' figure was unverifiable and removed. The causal link from government spending to private growth is plausible but not directly proven, so directness lowered.",
        },
      ],
    },
    {
      id: "scientific-strategic-value",
      title: "Scientific & Strategic Value",
      short_summary:
        "The Mars Perseverance rover cost $2.7B. A crewed mission would cost $100B+. The rover does not inspire children to become engineers, but it also does not need life support.",
      icon_name: "Telescope" as const,
      skeptic_premise:
        "Robotic missions deliver most of the achievable science at a small fraction of the cost and none of the risk to human life. The ISS cost well over $100B and, for that price, has produced incremental rather than game-changing science. Space debris is a mounting, possibly self-reinforcing risk — ESA tracked roughly 35,000 objects in 2024 (about 26,000 of them debris larger than 10cm), with over a million fragments above 1cm estimated in orbit, threatening the satellites that underpin GPS, weather, and communications. And militarizing orbit accelerates a dangerous arms race.",
      proponent_rebuttal:
        "Much of this value has no Earth-bound substitute. Earth-observing satellites supply continuous, planet-wide climate and disaster data that ground networks cannot replicate. NASA's DART mission (a ~$324.5M test) measurably shifted asteroid Dimorphos's orbit, proving a real, if low-probability, planetary-defense capability. Orbital assets — positioning, reconnaissance, communications — are now core strategic infrastructure. The human-vs-robotic tradeoff is genuinely contested: robots win on cost-per-result, but crewed missions drive public engagement and STEM pipelines in ways uncrewed probes have not matched. The strongest case leans on the robotic and dual-use wins, not on assuming human missions pay for themselves.",
      crux: {
        id: "human-vs-robotic-value",
        title: "Human vs. Robotic Mission Value Comparison",
        description:
          "Systematic comparison of scientific output, cost-effectiveness, and strategic value between human and robotic space missions.",
        methodology:
          "Quantify scientific publications, discoveries, and technological capabilities per dollar spent for human vs. robotic missions. Include strategic defense value and public engagement metrics.",
        equation:
          "\\frac{\\text{Science Output}_{\\text{human}}}{\\text{Cost}_{\\text{human}}} \\overset{?}{>} \\frac{\\text{Science Output}_{\\text{robotic}}}{\\text{Cost}_{\\text{robotic}}}",
        verification_status: "theoretical" as const,
        cost_to_verify: "$200K (Comparative meta-analysis)",
        falsification: {
          supporter_flip:
            "If a systematic comparison showed robotic missions deliver essentially all the achievable science and strategic value per dollar — and the 'inspiration/STEM pipeline' benefit of crewed flight couldn't be measured or didn't materialize — the case for expensive human missions would collapse to robots-only.",
          skeptic_flip:
            "A skeptic who wants robots only should weigh that some value has no Earth substitute (continuous climate/disaster satellites, demonstrated asteroid deflection via DART) and that crewed missions drive public engagement and STEM interest in ways uncrewed probes haven't matched.",
          common_ground:
            "Both sides agree robotic missions win decisively on science-per-dollar and carry no risk to human life.",
          live_disagreement:
            "Whether the inspiration, STEM-pipeline, and long-run settlement value of crewed missions justify their order-of-magnitude higher cost, or whether that money simply buys more science as more robots.",
        },
      },
      evidence: [
        {
          id: "dart-success",
          title: "DART Asteroid Deflection Mission Succeeded",
          description:
            "NASA's DART mission (impact Sept 2022) shortened asteroid Dimorphos's orbit around Didymos by about 33 minutes — far exceeding the 73-second minimum success threshold. This demonstrated humanity can alter an asteroid's trajectory, addressing a real (if low-probability) existential risk. The DART project cost about $324.5M total, a fraction of the damage from even a small asteroid impact.",
          side: "for" as const,
          weight: {
            sourceReliability: 9,
            independence: 8,
            replicability: 6,
            directness: 8,
          },
          source: "NASA / Johns Hopkins APL (DART); mission cost via The Planetary Society",
          sourceUrl: "https://www.nasa.gov/news-release/nasa-confirms-dart-mission-impact-changed-asteroids-motion-in-space/",
          reasoning:
            "Independently verified result with clear planetary-defense implications. Cost ($324.5M) confirmed via The Planetary Society. Replicability limited as each asteroid is unique; weights kept high but trimmed from perfect 10s.",
        },
        {
          id: "robotic-vs-human-cost",
          title: "Robotic Missions Cost a Fraction of Crewed Missions",
          description:
            "The Mars Perseverance rover cost about $2.7B (lifecycle) and has operated since 2021. By contrast, estimates for a crewed Mars mission run into the hundreds of billions of dollars. The James Webb Space Telescope cost roughly $10B and has delivered a stream of major findings. Per-dollar, robotic missions deliver substantial science without the cost and risk of human life support — though the comparison mixes mission types with different goals.",
          side: "against" as const,
          weight: {
            sourceReliability: 7,
            independence: 6,
            replicability: 6,
            directness: 6,
          },
          source: "The Planetary Society (Perseverance ~$2.7B; JWST ~$10B)",
          sourceUrl: "https://www.planetary.org/space-policy/cost-of-perseverance",
          reasoning:
            "Costs are well-sourced (Planetary Society). De-inflated the 'crewed Mars = $500B-$1T' precision to 'hundreds of billions' (that range is an estimate, not a settled figure), and removed the unverifiable 'more transformative than any ISS experiment' comparison. Directness lowered since it compares different mission classes.",
        },
        {
          id: "climate-satellite-data",
          title: "Climate Satellites Provide Irreplaceable Earth Data",
          description:
            "NASA's Earth-observing satellites — including Landsat (land cover/deforestation since 1972), MODIS (vegetation, fires, surface change), and OCO-2 (atmospheric CO2 since 2014) — provide global-scale data used to track land change, sea level, ice, and carbon. This continuous, planet-wide coverage has no ground-based equivalent and feeds the climate models used worldwide.",
          side: "for" as const,
          weight: {
            sourceReliability: 9,
            independence: 7,
            replicability: 8,
            directness: 7,
          },
          source: "NASA Earthdata (MODIS, OCO-2, Landsat instrument pages)",
          sourceUrl: "https://www.earthdata.nasa.gov/data/instruments/modis",
          reasoning:
            "Landsat, MODIS, and OCO-2 are verified NASA missions providing exactly this data. Genuinely strong; independence trimmed slightly since NASA is both operator and primary advocate for the value of its own instruments.",
        },
        {
          id: "kessler-syndrome-risk",
          title: "Space Debris Threatens All Orbital Infrastructure",
          description:
            "The Kessler Syndrome describes a cascade where orbital collisions generate debris that triggers further collisions, potentially making parts of low Earth orbit unusable. Per ESA's Space Environment Report 2024, about 35,000 objects are tracked (roughly 26,000 of them debris larger than 10cm), with over one million fragments larger than 1cm estimated in orbit. SpaceX's Starlink constellation had added several thousand satellites by 2024, intensifying congestion. A cascade could damage satellites underpinning GPS, communications, and weather forecasting.",
          side: "against" as const,
          weight: {
            sourceReliability: 8,
            independence: 7,
            replicability: 6,
            directness: 6,
          },
          source: "ESA Space Environment Report 2024",
          sourceUrl: "https://www.esa.int/Space_Safety/Space_Debris/ESA_Space_Environment_Report_2024",
          reasoning:
            "Well-documented risk with credible ESA modeling. Updated the tracked-object count (~35,000+ per ESA 2024, not 27,000) and softened the Starlink figure to 'several thousand by 2024.' Directness moderate: it argues against unmanaged orbital expansion, not all space activity.",
        },
      ],
    },
  ],
};
