import type { Topic } from "@/lib/schemas/topic";

export const spaceExplorationValueData = {
  id: "space-exploration-value",
  title: "Is Space Exploration Worth It?",
  meta_claim:
    "Government-funded space exploration provides sufficient scientific, economic, and strategic returns to justify its cost.",
  status: "contested" as const,
  category: "science" as const,
  pillars: [
    {
      id: "economic-returns-spinoffs",
      title: "Economic Returns & Spin-offs",
      short_summary:
        "NASA claims $7-14 of economic return per dollar spent. Critics say that number relies on counting every downstream use of Teflon and memory foam.",
      icon_name: "Scale" as const,
      skeptic_premise:
        "NASA's $25B+ annual budget could fund universal pre-K, clean water infrastructure, or homelessness solutions with immediate, measurable impact. Space tourism is a billionaire's playground subsidized by taxpayers. Most spin-off claims are exaggerated — memory foam and Tang were not invented by NASA. The opportunity cost of space spending is enormous when millions lack basic needs.",
      proponent_rebuttal:
        "NASA estimates a 7:1 ROI through technology spin-offs including GPS navigation, water purification systems, medical imaging (CT/MRI advances), scratch-resistant lenses, and satellite communications. The space economy is projected to reach $1.8 trillion by 2035. Asteroid mining could solve rare-earth resource scarcity. SpaceX has already reduced launch costs by 90%, creating an entirely new commercial sector.",
      crux: {
        id: "space-economy-roi",
        title: "Space Investment ROI Calculation",
        description:
          "Comprehensive analysis of direct and indirect economic returns from government space spending, including spin-off technologies, commercial sector growth, and opportunity costs.",
        methodology:
          "Track all NASA-funded patents and their commercial applications. Calculate revenue generated by spin-off industries. Compare to counterfactual spending on social programs using economic multiplier models.",
        equation:
          "\\text{ROI} = \\frac{\\sum_{t} (\\text{Spin-off Revenue}_t + \\Delta\\text{GDP}_{\\text{space sector},t})}{\\sum_{t} \\text{Government Investment}_t}",
        verification_status: "theoretical" as const,
        cost_to_verify: "$500K (Comprehensive economic analysis)",
      },
      evidence: [
        {
          id: "nasa-spinoff-analysis",
          title: "NASA Spin-off Economic Impact Analysis",
          description:
            "NASA's annual Spinoff publication has profiled more than 2,000 technologies transferred to the private sector since 1976. The widely-cited '$7-14 (or higher) per dollar' ROI figures trace to NASA-commissioned econometric studies from the 1970s-90s that *assumed* an average rate of return for R&D rather than measuring spin-off revenue directly; critics note attribution is inflated since many technologies had parallel commercial development, and more conservative analyses suggest ratios closer to 2-3:1.",
          side: "for" as const,
          weight: {
            sourceReliability: 4,
            independence: 2,
            replicability: 3,
            directness: 4,
          },
          source: "NASA Spinoff (spinoff.nasa.gov); critique: John Pike / FAS",
          sourceUrl: "https://spinoff.nasa.gov/",
          reasoning:
            "The count of 2,000+ documented spin-offs is verifiable, but the high ROI multipliers are promotional estimates built on generous assumptions, not measured returns. Weights de-inflated: low independence (self-reported), low replicability (headline multiplier not reproducible from primary data).",
        },
        {
          id: "space-economy-projections",
          title: "Space Economy Projected at $1.8 Trillion by 2035",
          description:
            "A 2024 World Economic Forum report produced with McKinsey & Company projects the global space economy will grow from $630B (2023) to $1.8T by 2035 (~9% annual growth), driven by space-based and -enabled services in communications, positioning/navigation/timing, and Earth observation. This is a forecast, not a measured return on government spending.",
          side: "for" as const,
          weight: {
            sourceReliability: 6,
            independence: 6,
            replicability: 4,
            directness: 4,
          },
          source: "World Economic Forum & McKinsey, 'Space: The $1.8 Trillion Opportunity' (2024)",
          sourceUrl: "https://www.mckinsey.com/featured-insights/themes/the-space-economy-is-projected-to-reach-1-8-trillion-by-2035",
          reasoning:
            "Credible institutions, but the figure is a speculative 11-year forecast with wide error bars and only indirectly bears on whether *government* space spending pays off. Directness lowered accordingly; corrected the 2023 base ($630B, not $469B) and attribution (WEF/McKinsey, not Morgan Stanley).",
        },
        {
          id: "opportunity-cost-analysis",
          title: "Opportunity Cost: NASA's Budget vs. Social Programs",
          description:
            "NASA's enacted FY2024 budget was $24.875B — money that could instead fund domestic priorities such as childcare, water infrastructure, or housing. But the zero-sum framing is weak: NASA is only about 0.4% of the ~$6.8T federal budget, so its appropriation is far smaller than the cost of most universal social programs (e.g. universal pre-K is generally estimated in the tens of billions per year).",
          side: "against" as const,
          weight: {
            sourceReliability: 6,
            independence: 7,
            replicability: 6,
            directness: 5,
          },
          source: "The Planetary Society (NASA FY2024 budget, $24.875B)",
          sourceUrl: "https://www.planetary.org/space-policy/nasas-fy-2024-budget",
          reasoning:
            "Corrected the budget figure ($24.875B enacted, not $25.4B) and federal share (~0.4%, not 0.5%). De-inflated weights and softened the claim: the specific pre-K/clean-water/veteran-homelessness dollar substitutions were not traceable to CBO/Brookings, and the comparison rests on a contestable zero-sum assumption.",
        },
        {
          id: "private-space-revenue",
          title: "Commercial Space Revenue Now Dwarfs Government Spending",
          description:
            "Per the Space Foundation's Space Report 2024, the global space economy reached $570B in 2023, of which commercial revenue was about $445B (78%) versus ~$125B in government spending. SpaceX alone was valued at roughly $180B in a December 2023 tender offer. The large and growing commercial share suggests government seed investment helped catalyze a substantial private sector.",
          side: "for" as const,
          weight: {
            sourceReliability: 7,
            independence: 6,
            replicability: 6,
            directness: 5,
          },
          source: "Space Foundation, The Space Report 2024 Q2; SpaceX valuation via Bloomberg (Dec 2023)",
          sourceUrl: "https://www.spacefoundation.org/2024/07/30/the-space-report-2024-q2-shows-record-launch-pace-nasas-push-for-artemis-innovation-for-cleaner-rocket-fuels-new-tech-for-noaa-satellites/",
          reasoning:
            "Corrected outdated figures: commercial revenue is ~$445B of a $570B total (the old $384B was a stale Space Foundation number); the $8.5B 'private investment' figure was unverifiable and removed. The causal link from government spending to private growth is plausible but not directly proven, so directness lowered.",
        },
      ],
    },
    {
      id: "scientific-strategic-value",
      title: "Scientific & Strategic Value",
      short_summary:
        "The Mars Perseverance rover cost $2.7B. A crewed mission would cost $100B+. The rover does not inspire children to become engineers, but it also does not need life support.",
      icon_name: "Telescope" as const,
      skeptic_premise:
        "Robotic missions accomplish 90% of the science at 1% the cost of human missions. The ISS cost $150B and hasn't produced game-changing discoveries. Space debris is becoming a catastrophic risk — there are 27,000 tracked pieces of orbital junk threatening all satellite infrastructure. Militarizing space accelerates a dangerous arms race.",
      proponent_rebuttal:
        "Climate monitoring satellites are essential for understanding and responding to Earth's changing climate. NASA's DART mission successfully demonstrated asteroid deflection — an existential defense capability. Space capabilities provide critical military strategic advantage (GPS, reconnaissance, communications). Human missions drive public engagement and inspire STEM careers in ways robots cannot.",
      crux: {
        id: "human-vs-robotic-value",
        title: "Human vs. Robotic Mission Value Comparison",
        description:
          "Systematic comparison of scientific output, cost-effectiveness, and strategic value between human and robotic space missions.",
        methodology:
          "Quantify scientific publications, discoveries, and technological capabilities per dollar spent for human vs. robotic missions. Include strategic defense value and public engagement metrics.",
        equation:
          "\\frac{\\text{Science Output}_{\\text{human}}}{\\text{Cost}_{\\text{human}}} \\overset{?}{>} \\frac{\\text{Science Output}_{\\text{robotic}}}{\\text{Cost}_{\\text{robotic}}}",
        verification_status: "theoretical" as const,
        cost_to_verify: "$200K (Comparative meta-analysis)",
      },
      evidence: [
        {
          id: "dart-success",
          title: "DART Asteroid Deflection Mission Succeeded",
          description:
            "NASA's DART mission (impact Sept 2022) shortened asteroid Dimorphos's orbit around Didymos by about 33 minutes — far exceeding the 73-second minimum success threshold. This demonstrated humanity can alter an asteroid's trajectory, addressing a real (if low-probability) existential risk. The DART project cost about $324.5M total, a fraction of the damage from even a small asteroid impact.",
          side: "for" as const,
          weight: {
            sourceReliability: 9,
            independence: 8,
            replicability: 6,
            directness: 8,
          },
          source: "NASA / Johns Hopkins APL (DART); mission cost via The Planetary Society",
          sourceUrl: "https://www.nasa.gov/news-release/nasa-confirms-dart-mission-impact-changed-asteroids-motion-in-space/",
          reasoning:
            "Independently verified result with clear planetary-defense implications. Cost ($324.5M) confirmed via The Planetary Society. Replicability limited as each asteroid is unique; weights kept high but trimmed from perfect 10s.",
        },
        {
          id: "robotic-vs-human-cost",
          title: "Robotic Missions Cost a Fraction of Crewed Missions",
          description:
            "The Mars Perseverance rover cost about $2.7B (lifecycle) and has operated since 2021. By contrast, estimates for a crewed Mars mission run into the hundreds of billions of dollars. The James Webb Space Telescope cost roughly $10B and has delivered a stream of major findings. Per-dollar, robotic missions deliver substantial science without the cost and risk of human life support — though the comparison mixes mission types with different goals.",
          side: "against" as const,
          weight: {
            sourceReliability: 7,
            independence: 6,
            replicability: 6,
            directness: 6,
          },
          source: "The Planetary Society (Perseverance ~$2.7B; JWST ~$10B)",
          sourceUrl: "https://www.planetary.org/space-policy/cost-of-perseverance",
          reasoning:
            "Costs are well-sourced (Planetary Society). De-inflated the 'crewed Mars = $500B-$1T' precision to 'hundreds of billions' (that range is an estimate, not a settled figure), and removed the unverifiable 'more transformative than any ISS experiment' comparison. Directness lowered since it compares different mission classes.",
        },
        {
          id: "climate-satellite-data",
          title: "Climate Satellites Provide Irreplaceable Earth Data",
          description:
            "NASA's Earth-observing satellites — including Landsat (land cover/deforestation since 1972), MODIS (vegetation, fires, surface change), and OCO-2 (atmospheric CO2 since 2014) — provide global-scale data used to track land change, sea level, ice, and carbon. This continuous, planet-wide coverage has no ground-based equivalent and feeds the climate models used worldwide.",
          side: "for" as const,
          weight: {
            sourceReliability: 9,
            independence: 7,
            replicability: 8,
            directness: 7,
          },
          source: "NASA Earthdata (MODIS, OCO-2, Landsat instrument pages)",
          sourceUrl: "https://www.earthdata.nasa.gov/data/instruments/modis",
          reasoning:
            "Landsat, MODIS, and OCO-2 are verified NASA missions providing exactly this data. Genuinely strong; independence trimmed slightly since NASA is both operator and primary advocate for the value of its own instruments.",
        },
        {
          id: "kessler-syndrome-risk",
          title: "Space Debris Threatens All Orbital Infrastructure",
          description:
            "The Kessler Syndrome describes a cascade where orbital collisions generate debris that triggers further collisions, potentially making parts of low Earth orbit unusable. Per ESA's Space Environment Report 2024, about 35,000 objects are tracked (roughly 26,000 of them debris larger than 10cm), with over one million fragments larger than 1cm estimated in orbit. SpaceX's Starlink constellation had added several thousand satellites by 2024, intensifying congestion. A cascade could damage satellites underpinning GPS, communications, and weather forecasting.",
          side: "against" as const,
          weight: {
            sourceReliability: 8,
            independence: 7,
            replicability: 6,
            directness: 6,
          },
          source: "ESA Space Environment Report 2024",
          sourceUrl: "https://www.esa.int/Space_Safety/Space_Debris/ESA_Space_Environment_Report_2024",
          reasoning:
            "Well-documented risk with credible ESA modeling. Updated the tracked-object count (~35,000+ per ESA 2024, not 27,000) and softened the Starlink figure to 'several thousand by 2024.' Directness moderate: it argues against unmanaged orbital expansion, not all space activity.",
        },
      ],
    },
  ],
};
