import type { Topic } from "@/lib/schemas/topic";

export const spaceExplorationValueData = {
  id: "space-exploration-value",
  title: "Is Space Exploration Worth It?",
  meta_claim:
    "Government-funded space exploration provides sufficient scientific, economic, and strategic returns to justify its cost.",
  status: "contested" as const,
  category: "science" as const,
  pillars: [
    {
      id: "economic-returns-spinoffs",
      title: "Economic Returns & Spin-offs",
      short_summary:
        "NASA claims $7-14 of economic return per dollar spent. Critics say that number relies on counting every downstream use of Teflon and memory foam.",
      icon_name: "Scale" as const,
      skeptic_premise:
        "NASA's $25B+ annual budget could fund universal pre-K, clean water infrastructure, or homelessness solutions with immediate, measurable impact. Space tourism is a billionaire's playground subsidized by taxpayers. Most spin-off claims are exaggerated — memory foam and Tang were not invented by NASA. The opportunity cost of space spending is enormous when millions lack basic needs.",
      proponent_rebuttal:
        "NASA estimates a 7:1 ROI through technology spin-offs including GPS navigation, water purification systems, medical imaging (CT/MRI advances), scratch-resistant lenses, and satellite communications. The space economy is projected to reach $1.8 trillion by 2035. Asteroid mining could solve rare-earth resource scarcity. SpaceX has already reduced launch costs by 90%, creating an entirely new commercial sector.",
      crux: {
        id: "space-economy-roi",
        title: "Space Investment ROI Calculation",
        description:
          "Comprehensive analysis of direct and indirect economic returns from government space spending, including spin-off technologies, commercial sector growth, and opportunity costs.",
        methodology:
          "Track all NASA-funded patents and their commercial applications. Calculate revenue generated by spin-off industries. Compare to counterfactual spending on social programs using economic multiplier models.",
        equation:
          "\\text{ROI} = \\frac{\\sum_{t} (\\text{Spin-off Revenue}_t + \\Delta\\text{GDP}_{\\text{space sector},t})}{\\sum_{t} \\text{Government Investment}_t}",
        verification_status: "theoretical" as const,
        cost_to_verify: "$500K (Comprehensive economic analysis)",
      },
      evidence: [
        {
          id: "nasa-spinoff-analysis",
          title: "NASA Spin-off Economic Impact Analysis",
          description:
            "NASA's annual Spinoff publication documents over 2,000 technologies transferred to the private sector. Independent analysis estimates these generate $7-14 in economic activity per dollar invested, though critics argue attribution is inflated since many technologies had parallel commercial development.",
          side: "for" as const,
          weight: {
            sourceReliability: 6,
            independence: 4,
            replicability: 5,
            directness: 6,
          },
          source: "NASA Office of Technology Transfer",
          reasoning:
            "NASA-produced data has inherent bias, but the breadth of documented spin-offs is substantial. Independence score is low due to self-reporting.",
        },
        {
          id: "space-economy-projections",
          title: "Space Economy Projected at $1.8 Trillion by 2035",
          description:
            "Morgan Stanley, McKinsey, and the World Economic Forum project the global space economy will grow from $469B (2023) to $1.8T by 2035. Growth is driven by satellite broadband, Earth observation, in-space manufacturing, and space tourism.",
          side: "for" as const,
          weight: {
            sourceReliability: 7,
            independence: 7,
            replicability: 5,
            directness: 5,
          },
          source: "Morgan Stanley Space Economy Report",
          reasoning:
            "Credible financial institutions, but projections are speculative and assume continued government investment as a catalyst.",
        },
        {
          id: "opportunity-cost-analysis",
          title: "Opportunity Cost: $25B Could Fund Universal Pre-K",
          description:
            "NASA's $25.4B annual budget (2024) exceeds the estimated $22B needed for universal pre-K in the US, $10B for clean water infrastructure repairs, or $20B to end veteran homelessness. Every dollar spent in space is a dollar not spent on immediate human needs with proven returns.",
          side: "against" as const,
          weight: {
            sourceReliability: 8,
            independence: 8,
            replicability: 8,
            directness: 7,
          },
          source: "Congressional Budget Office, Brookings Institution",
          reasoning:
            "Valid economic comparison, though it assumes a zero-sum budget which isn't strictly accurate — NASA's budget is 0.5% of federal spending.",
        },
        {
          id: "private-space-revenue",
          title: "Private Space Industry Revenue Exceeds Government Spending",
          description:
            "The commercial space industry generated $384B in revenue in 2023, with SpaceX alone valued at $180B. Private investment in space companies reached $8.5B in 2023. This suggests government seed investment has catalyzed a self-sustaining industry.",
          side: "for" as const,
          weight: {
            sourceReliability: 7,
            independence: 7,
            replicability: 7,
            directness: 6,
          },
          source: "Space Foundation, Bryce Tech",
          reasoning:
            "Industry data is solid; the causal link between government spending and private growth is plausible but not fully proven.",
        },
      ],
    },
    {
      id: "scientific-strategic-value",
      title: "Scientific & Strategic Value",
      short_summary:
        "The Mars Perseverance rover cost $2.7B. A crewed mission would cost $100B+. The rover does not inspire children to become engineers, but it also does not need life support.",
      icon_name: "Telescope" as const,
      skeptic_premise:
        "Robotic missions accomplish 90% of the science at 1% the cost of human missions. The ISS cost $150B and hasn't produced game-changing discoveries. Space debris is becoming a catastrophic risk — there are 27,000 tracked pieces of orbital junk threatening all satellite infrastructure. Militarizing space accelerates a dangerous arms race.",
      proponent_rebuttal:
        "Climate monitoring satellites are essential for understanding and responding to Earth's changing climate. NASA's DART mission successfully demonstrated asteroid deflection — an existential defense capability. Space capabilities provide critical military strategic advantage (GPS, reconnaissance, communications). Human missions drive public engagement and inspire STEM careers in ways robots cannot.",
      crux: {
        id: "human-vs-robotic-value",
        title: "Human vs. Robotic Mission Value Comparison",
        description:
          "Systematic comparison of scientific output, cost-effectiveness, and strategic value between human and robotic space missions.",
        methodology:
          "Quantify scientific publications, discoveries, and technological capabilities per dollar spent for human vs. robotic missions. Include strategic defense value and public engagement metrics.",
        equation:
          "\\frac{\\text{Science Output}_{\\text{human}}}{\\text{Cost}_{\\text{human}}} \\overset{?}{>} \\frac{\\text{Science Output}_{\\text{robotic}}}{\\text{Cost}_{\\text{robotic}}}",
        verification_status: "verified" as const,
        cost_to_verify: "$200K (Comparative meta-analysis)",
      },
      evidence: [
        {
          id: "dart-success",
          title: "DART Asteroid Deflection Mission Succeeded",
          description:
            "NASA's DART mission (2022) successfully altered asteroid Dimorphos's orbit by 33 minutes — far exceeding the 73-second minimum. This proved humanity can defend against asteroid impacts, an existential risk. The mission cost $325M, a fraction of the damage from even a small asteroid impact.",
          side: "for" as const,
          weight: {
            sourceReliability: 10,
            independence: 9,
            replicability: 7,
            directness: 9,
          },
          source: "NASA, Johns Hopkins APL, Nature",
          reasoning:
            "Independently verified result with clear existential-defense implications. Replicability slightly limited as each asteroid is unique.",
        },
        {
          id: "robotic-vs-human-cost",
          title: "Robotic Missions Cost 1% of Human Missions",
          description:
            "Mars Perseverance rover cost $2.7B and has operated for 3+ years. A crewed Mars mission would cost an estimated $500B-$1T. The James Webb Space Telescope ($10B) has produced more transformative science than any ISS experiment. Per-dollar scientific output strongly favors robotic missions.",
          side: "against" as const,
          weight: {
            sourceReliability: 8,
            independence: 8,
            replicability: 7,
            directness: 8,
          },
          source: "NASA JPL, National Academies of Sciences",
          reasoning:
            "Strong cost comparison with reliable data; somewhat limited by comparing different mission types with different objectives.",
        },
        {
          id: "climate-satellite-data",
          title: "Climate Satellites Provide Irreplaceable Earth Data",
          description:
            "NASA's Earth-observing satellites (Landsat, MODIS, OCO-2) provide the primary data for tracking deforestation, sea level rise, ice sheet loss, and atmospheric CO2. This data underpins climate models used by every nation. No ground-based alternative exists for global-scale monitoring.",
          side: "for" as const,
          weight: {
            sourceReliability: 9,
            independence: 8,
            replicability: 8,
            directness: 8,
          },
          source: "NASA Earth Science Division, IPCC",
          reasoning:
            "Widely accepted and directly useful; satellite climate data is genuinely irreplaceable for global monitoring.",
        },
        {
          id: "kessler-syndrome-risk",
          title: "Space Debris Threatens All Orbital Infrastructure",
          description:
            "The Kessler Syndrome describes a cascade where orbital collisions generate debris that causes more collisions, potentially making low Earth orbit unusable. There are 27,000+ tracked debris objects and millions of smaller pieces. Starlink alone has added 5,000+ satellites. A single cascade event could destroy GPS, communications, and weather satellites worth trillions.",
          side: "against" as const,
          weight: {
            sourceReliability: 8,
            independence: 8,
            replicability: 6,
            directness: 7,
          },
          source: "ESA Space Debris Office, NASA ODPO",
          reasoning:
            "Well-documented risk with credible modeling; directness is moderate since it argues against unmanaged expansion rather than all space activity.",
        },
      ],
    },
  ],
};
