import { useId } from "react";
import type { AnalyzeExecution } from "@/lib/analyze/contracts";

interface AnalyzeExecutionNoticeProps {
  execution: AnalyzeExecution;
}

function analysisCopy(execution: AnalyzeExecution["analysis"]): string {
  if (execution.actual === "live") {
    return "This analysis was generated by a live AI model.";
  }
  if (execution.requested === "live") {
    return "Live AI analysis was unavailable, so programmatic rules were used.";
  }
  return "This analysis used programmatic rules, not a live AI model.";
}

function judgingCopy(execution: AnalyzeExecution["judging"]): string | null {
  if (execution.actual === "disabled") return null;
  if (execution.actual === "skipped") {
    return "Judging was skipped because no structured arguments were available.";
  }
  if (execution.actual === "live") {
    return "Judging used live AI models.";
  }
  if (execution.requested === "live") {
    return "Live AI judging was unavailable, so programmatic scoring rules were used.";
  }
  return "Judging used programmatic scoring rules, not live AI models.";
}

function processingCopy(execution: AnalyzeExecution): string {
  if (execution.analysis.actual === "live") {
    return "Argumend does not store your pasted source text. It was sent to the configured model provider for this analysis request.";
  }
  if (execution.analysis.fallbackCode === "ANALYSIS_PROVIDER_ERROR") {
    return "Argumend does not store your pasted source text. A live analysis request was attempted before programmatic fallback, so the configured provider’s data handling may apply.";
  }
  if (execution.judging.actual === "live") {
    return "Argumend does not store your pasted source text. The configured model provider received extracted argument data for judging.";
  }
  if (execution.judging.fallbackCode === "JUDGING_PROVIDER_ERROR") {
    return "Argumend does not store your pasted source text. Live judging was attempted with extracted argument data before programmatic fallback.";
  }
  return "Argumend does not store your pasted source text. No model provider received it for this report.";
}

export function AnalyzeExecutionNotice({ execution }: AnalyzeExecutionNoticeProps) {
  const headingId = useId();
  const judgment = judgingCopy(execution.judging);

  return (
    <section
      aria-labelledby={headingId}
      className="rounded-xl border border-stone-200/70 dark:border-[var(--border-default)] bg-stone-50/80 dark:bg-[var(--bg-surface)] px-4 py-3"
    >
      <h3
        id={headingId}
        className="text-sm font-semibold text-stone-800 dark:text-stone-200"
      >
        How this report was produced
      </h3>
      <div className="flex flex-wrap gap-2">
        <span className="mt-2 rounded-full bg-white dark:bg-[var(--bg-card)] border border-stone-200 dark:border-[var(--border-default)] px-2.5 py-1 text-xs font-medium text-stone-700 dark:text-stone-300">
          {execution.analysis.actual === "live"
            ? "Live AI analysis"
            : "Programmatic analysis"}
        </span>
        {execution.judging.actual !== "disabled" && (
          <span className="mt-2 rounded-full bg-white dark:bg-[var(--bg-card)] border border-stone-200 dark:border-[var(--border-default)] px-2.5 py-1 text-xs font-medium text-stone-700 dark:text-stone-300">
            {execution.judging.actual === "live"
              ? "Live AI judging"
              : execution.judging.actual === "offline"
                ? "Programmatic judging"
                : "Judging skipped"}
          </span>
        )}
      </div>
      <p className="mt-2 text-sm text-stone-600 dark:text-stone-400">
        {analysisCopy(execution.analysis)}{judgment ? ` ${judgment}` : ""}
      </p>
      <p className="mt-1 text-xs leading-relaxed text-stone-500 dark:text-stone-500">
        {processingCopy(execution)}
      </p>
    </section>
  );
}
