/**
 * Pre-computed judge verdicts for all mock debates.
 *
 * Generated by: npx tsx scripts/generate-verdicts.ts
 * Judge panel: 3 Claude personas (Analyst, Reviewer, Arbiter)
 *
 * The raw data lives in mockVerdicts.json (~650 KB) so that bundlers can
 * tree-shake or lazy-load it instead of inlining it into every client chunk.
 *
 * DO NOT EDIT the JSON — regenerate with the script above.
 */

import type { JudgingResult } from "@/lib/judge/rubric";
import _data from "./mockVerdicts.json";

export const MOCK_VERDICTS: Record<string, JudgingResult> = _data as Record<
  string,
  JudgingResult
>;

/**
 * Get pre-computed verdict for a topic.
 */
export function getMockVerdict(topicId: string): JudgingResult | undefined {
  return MOCK_VERDICTS[topicId];
}

/**
 * Check if a pre-computed verdict exists for a topic.
 */
export function hasMockVerdict(topicId: string): boolean {
  return topicId in MOCK_VERDICTS;
}
