/**
 * Tier 6.3 — Confidence-score audit.
 *
 * Re-derives each topic's confidence purely from its evidence weights and
 * compares it to the score actually exposed on the topic. buildTopic() takes
 * `max(computed, original)` for "settled" topics, so any gap means the topic is
 * leaning on a hardcoded/floor value rather than its evidence. Writes a ranked
 * discrepancy report to docs/reviews/confidence-audit.md.
 */
import { writeFileSync } from "node:fs";
import { topics } from "../data/topics";
import { computeConfidenceScore } from "../lib/schemas/topic";

type Row = {
  id: string;
  title: string;
  status: string;
  stored: number;
  computed: number;
  gap: number;
};

const rows: Row[] = topics.map((t) => {
  const computed = computeConfidenceScore(t.pillars);
  return {
    id: t.id,
    title: t.title,
    status: t.status,
    stored: t.confidence_score,
    computed,
    gap: t.confidence_score - computed,
  };
});

const flagged = rows
  .filter((r) => Math.abs(r.gap) >= 8)
  .sort((a, b) => Math.abs(b.gap) - Math.abs(a.gap));

const lines: string[] = [];
lines.push("# Confidence-Score Audit (Tier 6.3)");
lines.push("");
lines.push(
  "Generated by `scripts/audit-confidence.ts`. `computed` = confidence derived purely from evidence weights via `computeConfidenceScore(pillars)`. `stored` = the score the topic exposes. A large positive gap means the displayed confidence is higher than the evidence alone supports (usually a `settled`-status floor).",
);
lines.push("");
lines.push(`- Topics audited: **${rows.length}**`);
lines.push(`- Flagged (|gap| ≥ 8): **${flagged.length}**`);
lines.push("");
if (flagged.length === 0) {
  lines.push(
    "✅ No topic's displayed confidence diverges from its evidence-derived score by 8+ points. Scores are well-calibrated to the mapped evidence.",
  );
  lines.push("");
}
const topGaps = [...rows]
  .sort((a, b) => Math.abs(b.gap) - Math.abs(a.gap))
  .slice(0, 15);
lines.push("## Largest gaps (top 15, for transparency)");
lines.push("");
lines.push("| Topic | Status | Stored | Computed | Gap |");
lines.push("|---|---|---:|---:|---:|");
for (const r of topGaps) {
  lines.push(
    `| ${r.title} (\`${r.id}\`) | ${r.status} | ${r.stored} | ${r.computed} | ${r.gap > 0 ? "+" : ""}${r.gap} |`,
  );
}
lines.push("");
lines.push("## Notes");
lines.push(
  "- Large positive gaps on `settled` topics are usually intentional (the evidence sample is small but the question is genuinely settled — e.g. moon landing). Verify the floor is justified.",
);
lines.push(
  "- Positive gaps on `contested` topics are the real concern: the displayed score overstates confidence relative to the mapped evidence. Prioritize these.",
);
lines.push(
  "- Negative gaps mean the evidence supports MORE confidence than shown — consider whether the status/score should rise.",
);

writeFileSync("docs/reviews/confidence-audit.md", lines.join("\n"));
console.log(
  `Audited ${rows.length} topics; flagged ${flagged.length} with |gap| >= 8. Wrote docs/reviews/confidence-audit.md`,
);
// Surface the contested-topic overstatements inline for quick triage.
const contestedOver = flagged.filter((r) => r.status === "contested" && r.gap >= 8);
if (contestedOver.length) {
  console.log("Contested topics overstating confidence:");
  for (const r of contestedOver) {
    console.log(`  ${r.id}: stored ${r.stored} vs computed ${r.computed} (+${r.gap})`);
  }
}
