/**
 * Generate pre-computed verdicts for all mock debates.
 *
 * Usage: npx tsx scripts/generate-verdicts.ts
 */

/* eslint-disable no-console */

import { MOCK_DEBATES } from "../data/mockDebates";
import { judgeWithClaudePanel } from "../lib/judge/panel";
import type { JudgingResult } from "../lib/judge/rubric";
import * as fs from "fs";
import * as path from "path";

const verdicts: Record<string, JudgingResult> = {};
const topicIds = Object.keys(MOCK_DEBATES);

console.log(`Judging ${topicIds.length} debates with 3-Claude panel...\n`);

for (const topicId of topicIds) {
  const messages = MOCK_DEBATES[topicId];
  if (!messages || messages.length === 0) {
    console.log(`  SKIP ${topicId} (no messages)`);
    continue;
  }
  const result = judgeWithClaudePanel(messages, topicId);
  verdicts[topicId] = result;
  const winLabel = result.winner === "for" ? "FOR" : result.winner === "against" ? "AGAINST" : "DRAW";
  const forAvg = result.aggregatedScores.for.average.toFixed(2);
  const againstAvg = result.aggregatedScores.against.average.toFixed(2);
  const consensusTag = result.hasConsensus ? "unanimous" : "split";
  console.log(`  ${topicId}: ${winLabel} (${forAvg} vs ${againstAvg}) [${consensusTag}]`);
}

// Write the output file
const outputPath = path.join(__dirname, "..", "data", "mockVerdicts.ts");

const header = `/**
 * Pre-computed judge verdicts for all mock debates.
 *
 * Generated by: npx tsx scripts/generate-verdicts.ts
 * Judge panel: 3 Claude personas (Analyst, Reviewer, Arbiter)
 *
 * DO NOT EDIT — regenerate with the script above.
 */

import type { JudgingResult } from "@/lib/judge/rubric";

`;

const body = `export const MOCK_VERDICTS: Record<string, JudgingResult> = ${JSON.stringify(verdicts, null, 2)};

/**
 * Get pre-computed verdict for a topic.
 */
export function getMockVerdict(topicId: string): JudgingResult | undefined {
  return MOCK_VERDICTS[topicId];
}

/**
 * Check if a pre-computed verdict exists for a topic.
 */
export function hasMockVerdict(topicId: string): boolean {
  return topicId in MOCK_VERDICTS;
}
`;

fs.writeFileSync(outputPath, header + body, "utf-8");
console.log(`\nWrote ${Object.keys(verdicts).length} verdicts to data/mockVerdicts.ts`);
